### ISSUE TITLE
jtag cannot detect cortex-M3 device

### ISSUE THREAD

**Issue by slot867** [Qirun/ARM_Cortex-M3#2]
I tested cortex_m3vivado.rar on Arty-S7, assigning Jlink-JTAG pins to  PMOD JD. However, in Keil uvision ide, **options for target** cannot detect cortex-M3 device. Please help . thanks in advance.

JD

**Comment by Jeacy** [comment]
m3 does not support jtag debugging

**Comment by slot867** [comment]
But in your project
